---
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-network-application
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - ./config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
  #    - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
      image: docker.io/mongo:7.0.11
      container_name: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: "mongo"
        MONGO_INITDB_ROOT_PASSWORD: "mongo"
      volumes:
        - ./mongo:/data/db
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  mongo-express:
    image: mongo-express:1.0.2-18-alpine3.18
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    restart: unless-stopped
